"""
    Swagger Petstore - OpenAPI 3.0

    This is a sample Pet Store Server based on the OpenAPI 3.0 specification.  You can find out more about Swagger at [https://swagger.io](https://swagger.io). In the third iteration of the pet store, we've switched to the design first approach! You can now help us improve the API whether it's by making changes to the definition itself or to the code. That way, with time, we can improve the API in general, and expose some of the new features in OAS3.  _If you're looking for the Swagger 2.0/OAS 2.0 version of Petstore, then click [here](https://editor.swagger.io/?url=https://petstore.swagger.io/v2/swagger.yaml). Alternatively, you can load via the `Edit > Load Petstore OAS 2.0` menu option!_  Some useful links: - [The Pet Store repository](https://github.com/swagger-api/swagger-petstore) - [The source API definition for the Pet Store](https://github.com/swagger-api/swagger-petstore/blob/master/src/main/resources/openapi.yaml)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: edson@michaque.com
    Generated by: https://openapi-generator.tech
"""


import unittest

import buziv2
from buziv2.api.sms_api import SmsApi  # noqa: E501


class TestSmsApi(unittest.TestCase):
    """SmsApi unit test stubs"""

    def setUp(self):
        self.api = SmsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_cancel_message(self):
        """Test case for cancel_message

        Cancel a message  # noqa: E501
        """
        pass

    def test_create_message(self):
        """Test case for create_message

        Create Message  # noqa: E501
        """
        pass

    def test_create_pricing(self):
        """Test case for create_pricing

        Create network price  # noqa: E501
        """
        pass

    def test_delete_message(self):
        """Test case for delete_message

        Deletes a message  # noqa: E501
        """
        pass

    def test_get_message(self):
        """Test case for get_message

        Get message  # noqa: E501
        """
        pass

    def test_get_network(self):
        """Test case for get_network

        Get network  # noqa: E501
        """
        pass

    def test_get_pricing(self):
        """Test case for get_pricing

        List network rates  # noqa: E501
        """
        pass

    def test_list_messages(self):
        """Test case for list_messages

        List messages  # noqa: E501
        """
        pass

    def test_list_networks(self):
        """Test case for list_networks

        List networks  # noqa: E501
        """
        pass

    def test_send_message(self):
        """Test case for send_message

        Sends a message  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
